
name: Test_Windows

on: [pull_request]

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
          
      - name: Build server
        shell: bash
        working-directory: ./minimal/server/org.eclipse.glsp.example.minimal
        run: mvn -B -Pm2 clean verify --file pom.xml

      - name: Build client
        shell: bash
        working-directory: ./minimal/client
        run: yarn

